DROP TABLE TB01_USERS;

CREATE TABLE TB01_USERS (
	ID INT NOT NULL AUTO_INCREMENT,
	LOGIN VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(128),
	HASH_VALIDATION VARCHAR(32),
	INSCRIPTION_DATE DATE,
	GROUP_ID INT NOT NULL,
	ID_MEMBER INT,
	POKERSPHERE_ID INT,
	PRIMARY KEY (ID)
)
ENGINE=MyISAM;

CREATE UNIQUE INDEX TB01_LOGIN
ON TB01_USERS (LOGIN);

CREATE UNIQUE INDEX TB01_EMAIL
ON TB01_USERS (EMAIL);

CREATE INDEX TB01_PASSWORD
ON TB01_USERS (PASSWORD);

DROP TABLE TB02_GROUP;

CREATE TABLE TB02_GROUP (
	ID INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(50) NOT NULL,
	PRIMARY KEY (ID)
)
ENGINE=MyISAM;

CREATE UNIQUE INDEX TB02_NAME
ON TB02_GROUP (NAME);

DROP TABLE TB03_MEMBER;

CREATE TABLE TB03_MEMBER (
	ID INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(50) NOT NULL,
	FIRSTNAME VARCHAR(50),
	PSEUDO VARCHAR(50),
	BIRTH_DATE DATETIME,
	ADRESS VARCHAR(100),
	ZIP_CODE VARCHAR(20),
	CITY VARCHAR(50),
	EMAIL VARCHAR(100),
	PHONE VARCHAR(20),
	KOSMOS INT,
	PICTURE LONGTEXT,
	CLUB VARCHAR(50),
	CREATION_DATE DATETIME NOT NULL,
	DELETED VARCHAR(1) NOT NULL,
	ID_SPONSOR INT,
	POKERSPHERE_ID INT,
	PLAQUE_IMMATRICULATION VARCHAR(20),
	PRIMARY KEY (ID)
)
ENGINE=MyISAM;

CREATE UNIQUE INDEX TB03_NAME_FIRSTNAME_EMAIL
ON TB03_MEMBER (NAME,FIRSTNAME,EMAIL);

DROP TABLE TB04_ADHESION;

CREATE TABLE TB04_ADHESION (
	ID INT NOT NULL AUTO_INCREMENT,
	ID_MEMBER INT NOT NULL,
	VALUE INT NOT NULL,
	OPERATION_DATE DATETIME NOT NULL,
	ENABLE_DATE DATETIME NOT NULL,
	DISABLE_DATE DATETIME NOT NULL,
	VIP VARCHAR(1) NOT NULL,
	PRIX DECIMAL(10,2) NOT NULL,
	PRIMARY KEY (ID)
)
ENGINE=MyISAM;

DROP TABLE TB05_KOSMOS;

CREATE TABLE TB05_KOSMOS (
	ID INT NOT NULL AUTO_INCREMENT,
	ID_MEMBER INT NOT NULL,
	VALUE INT NOT NULL,
	OPERATION_DATE DATETIME NOT NULL,
	CREDIT VARCHAR(1) NOT NULL,
	REASON VARCHAR(3) NOT NULL,
	COMMENT VARCHAR(255),
	PRIMARY KEY (ID)
)
ENGINE=MyISAM;

CREATE INDEX I05_ID_MEMBER
ON TB05_KOSMOS (ID_MEMBER);

/*CREATE TRIGGER ins_Kosmos AFTER INSERT ON TB05_KOSMOS
FOR EACH ROW
UPDATE TB03_MEMBER T3 SET KOSMOS = KOSMOS + CASE new.CREDIT WHEN 1 THEN 1 ELSE -1 END * new.VALUE
WHERE T3.ID = new.ID_MEMBER;

CREATE TRIGGER del_Kosmos AFTER DELETE ON TB05_KOSMOS
FOR EACH ROW
UPDATE TB03_MEMBER T3 SET KOSMOS = KOSMOS + CASE old.CREDIT WHEN 1 THEN -1 ELSE 1 END * old.VALUE
WHERE T3.ID = old.ID_MEMBER;

CREATE TRIGGER upd_Kosmos AFTER UPDATE ON TB05_KOSMOS
FOR EACH ROW
UPDATE TB03_MEMBER T3 SET KOSMOS = KOSMOS + CASE old.CREDIT WHEN 1 THEN -1 ELSE 1 END * old.VALUE + CASE new.CREDIT WHEN 1 THEN 1 ELSE -1 END * new.VALUE
WHERE T3.ID = new.ID_MEMBER;*/

DROP TABLE TB06_TOURNAMENT;

CREATE TABLE TB06_TOURNAMENT (
	ID INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100) NOT NULL ,
	BEGIN_DATE DATETIME NOT NULL ,
	END_REGISTRATION_DATE DATETIME NOT NULL ,
	BUY_IN INT NOT NULL ,
	NB_PLAYERS INT NOT NULL ,
	VARIANTE INT NOT NULL ,
	VALIDATED INT NOT NULL,
	COMMENT VARCHAR(500),
	PRIVATE INT NOT NULL,
	TYPE INT NOT NULL,
	POKERSPHERE_ID INT,
	SENT_TO_RANKINGHERO INT NOT NULL DEFAULT 0,
	ATTACHED_TOURNAMENT INT,
	PRIMARY KEY(ID)
) 
ENGINE = MyISAM ;

DROP TABLE TB07_TOURNAMENT_REGISTRATION;

CREATE TABLE TB07_TOURNAMENT_REGISTRATION (
	ID_TOURNAMENT INT NOT NULL,
	ID_MEMBER INT NOT NULL,
	REGISTRATION_DATE DATETIME NOT NULL ,
	IS_LATE INT NOT NULL ,
	IS_ARRIVED INT NOT NULL,
	ID_BUY_IN INT,
	ID_GAIN INT,
	POSITION INT,
	PRIMARY KEY(ID_TOURNAMENT, ID_MEMBER)
) 
ENGINE = MyISAM ;

ALTER TABLE TB07_TOURNAMENT_REGISTRATION
ADD COLUMN ID_BUY_IN INT,
ADD COLUMN ID_GAIN INT,
ADD COLUMN POSITION INT;

DROP TABLE TB08_ROOM_ONLINE;

CREATE TABLE TB08_ROOM_ONLINE (
	ID INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(50),
	ORDRE INT,
	LIEN_AFFILIATION VARCHAR(100),
	PRIMARY KEY(ID)
) 
ENGINE = MyISAM ;

DROP TABLE TB09_MEMBER_ROOM;

CREATE TABLE TB09_MEMBER_ROOM (
	ID_MEMBER INT NOT NULL,
	ID_ROOM INT NOT NULL,
	PSEUDO VARCHAR(50),
	PUBLIC INT NOT NULL,
	PRIMARY KEY(ID_MEMBER, ID_ROOM)
) 
ENGINE = MyISAM ;

DROP TABLE TB10_AMBASSADEUR;

CREATE TABLE TB10_AMBASSADEUR (
	ID INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(50) NOT NULL,
	FIRSTNAME VARCHAR(50) NOT NULL,
	LINK VARCHAR(100),
	PRIMARY KEY(ID)
)
ENGINE = MyISAM ;

DROP TABLE TB11_VOTE_AMBASSADEUR;

CREATE TABLE TB11_VOTE_AMBASSADEUR (
	ID_MEMBER INT NOT NULL,
	ID_AMBASSADEUR INT NOT NULL--,
	--PRIMARY KEY(ID_MEMBER)
)
ENGINE = MyISAM ;

DROP TABLE TB12_TOURNAMENT_TEMPLATE;

CREATE TABLE TB12_TOURNAMENT_TEMPLATE (
	ID INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100) NOT NULL ,
	BUY_IN INT NOT NULL ,
	NB_PLAYERS INT NOT NULL ,
	VARIANTE INT NOT NULL ,
	COMMENT VARCHAR(500),
	POKERSPHERE_ID INT,
	PRIMARY KEY(ID)
) 
ENGINE = MyISAM ;

DROP TABLE TB13_MEMBER_CARD;

CREATE TABLE TB13_MEMBER_CARD (
	ID_MEMBER INT NOT NULL,
	CARD_NUMBER VARCHAR(100),
	PRIMARY KEY(ID_MEMBER),
	UNIQUE INDEX (CARD_NUMBER)
) 
ENGINE = MyISAM ;

DROP TABLE TB14_LOG;

CREATE TABLE TB14_LOG (
	ID_MEMBER INT NOT NULL,
	EVENT VARCHAR(500) NOT NULL,
	EVENT_DATE DATETIME NOT NULL
) 
ENGINE = MyISAM ;

DROP TABLE TB15_GAIN_SPONSOR;

CREATE TABLE TB15_GAIN_SPONSOR (
	ID INT NOT NULL AUTO_INCREMENT,
	LAUNCHING INT NOT NULL COMMENT '0 Déclenchement lors de la soirée découverte\n1 Déclenchement lors de la 1ère inscription',
	TYPE_GODSON_GAIN INT NOT NULL COMMENT '0 Gain en Kosmos\n 1 Gain en jour d''abonnement\n 2 Bonus en Kosmos',
	GODSON_GAIN INT NOT NULL,
	TYPE_SPONSOR_GAIN INT NOT NULL COMMENT '0 Gain en Kosmos\n 1 Gain en jour d''abonnement\n 2 Bonus en Kosmos',
	SPONSOR_GAIN INT NOT NULL,
	NB_MONTH_FIRST_MEMBERSHIP INT,
	PRIMARY KEY(ID)
)
ENGINE = myISAM;

INSERT INTO TB15_GAIN_SPONSOR(LAUNCHING,TYPE_GODSON_GAIN,GODSON_GAIN,TYPE_SPONSOR_GAIN,SPONSOR_GAIN,NB_MONTH_FIRST_MEMBERSHIP)
VALUES 
(0,0,1000,0,500,NULL),
(1,0,100,1,7,1),
(1,0,300,1,14,3),
(1,0,600,1,21,6),
(1,0,1200,1,28,12);

DROP TABLE TB16_CLUB;

CREATE TABLE TB16_CLUB (
	CLUB VARCHAR(50) NOT NULL ,
	POKERSPHERE_ID INT
) 
ENGINE = MyISAM ;

DROP TABLE TB17_FID_STATUT;

CREATE TABLE TB17_FID_STATUT (
	ID INT NOT NULL AUTO_INCREMENT,
	STATUT VARCHAR(50) NOT NULL ,
	SEUIL INT,
	PRIMARY KEY(ID)
) 
ENGINE = MyISAM ;

DROP TABLE TB18_FID_TYPE;

CREATE TABLE TB18_FID_TYPE (
	ID INT NOT NULL,
	NAME VARCHAR(50) NOT NULL ,
	RATIO FLOAT,
	VALUE INT,
	NB_MONTH INT,
	PRIMARY KEY(ID)
) 
ENGINE = MyISAM ;

INSERT INTO TB18_FID_TYPE(ID,NAME,RATIO,VALUE,NB_MONTH)
VALUES 
(0,'Mois Abonnement',4,100,0),
(1,'Nombre de tournois',2,100,12),
(2,'Chargement Euros',1.5,100,3),
(3,'Parrainage',2,100,12),
(4,'Points Fidélité',1,100,1),
(5,'Achat avec Points de Fidélité',0,0,0);

DROP TABLE TB18_FID_ABONNEMENT_RATIO;

CREATE TABLE TB18_FID_ABONNEMENT_RATIO (
	NB_MONTH INT NOT NULL,
	RATIO FLOAT
) 
ENGINE = MyISAM;

INSERT INTO TB18_FID_ABONNEMENT_RATIO(NB_MONTH,RATIO)
VALUES 
(1,1), 
(3,220/60/3), 
(6,460/60/6), 
(12,1000/60/12); 

DROP TABLE TB19_FID_POINTS;

CREATE TABLE TB19_FID_POINTS (
	ID INT NOT NULL AUTO_INCREMENT,
	EVENT_DATE DATETIME NOT NULL,
	ID_MEMBER INT NOT NULL,
	ID_FID_TYPE INT,
	NB INT,
	COMMENT VARCHAR(100),
	ID_REF_OPERATION INT,
	PRIMARY KEY(ID)
) 
ENGINE = MyISAM ;

DROP TABLE TB20_RECAP;

CREATE TABLE TB20_RECAP (
	ID_MEMBER INT NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	FIRSTNAME VARCHAR(50),
	CREATION_DATE DATETIME,
	NB_TOURNAMENT_PLAYED INT NOT NULL,
	NB_WIN INT NOT NULL,
	NB_ITM INT NOT NULL,
	NB_KOSMOS_IN_BUY_IN INT NOT NULL,
	NB_KOSMOS_WIN_IN_TOURNAMENT INT NOT NULL,
	NB_FID_POINTS INT NOT NULL,
	PRIMARY KEY(ID_MEMBER)
) 
ENGINE = MyISAM ;

DROP TABLE TB21_DOT_TYPE;

CREATE TABLE TB21_DOT_TYPE (
	ID INT NOT NULL AUTO_INCREMENT,
	TYPE VARCHAR(50) NOT NULL ,
	DELETED CHAR(1) NOT NULL DEFAUlT 'N',
	PRIMARY KEY(ID)
) 
ENGINE = MyISAM ;

DROP TABLE TB22_DOT_DESC;

CREATE TABLE TB22_DOT_DESC (
	ID INT NOT NULL AUTO_INCREMENT,
	DESCRIPTION VARCHAR(100) NOT NULL ,
	DELETED CHAR(1) NOT NULL DEFAUlT 'N',
	PRIMARY KEY(ID)
) 
ENGINE = MyISAM ;

DROP TABLE TB23_TOURNAMENT_DOTATION;

CREATE TABLE TB23_TOURNAMENT_DOTATION (
	ID_TOURNAMENT INT NOT NULL,
	ID_MEMBER INT NOT NULL,
	ID_TYPE_DOTATION INT,
	VALUE INT,
	ID_DESCRIPTION_DOTATION INT
) 
ENGINE = MyISAM ;


DROP TABLE TBEXPORT_TOURNAMENT;

CREATE TABLE TBEXPORT_TOURNAMENT (
	ID INT NOT NULL,
	NAME VARCHAR(100) NOT NULL ,
	BEGIN_DATE DATETIME NOT NULL ,
	BUY_IN INT NOT NULL ,
	PRIMARY KEY(ID)
) 
ENGINE = MyISAM ;

DROP TABLE TBEXPORT_MEMBER;

CREATE TABLE TBEXPORT_MEMBER (
	ID INT NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	FIRSTNAME VARCHAR(50),
	PSEUDO VARCHAR(50),
	PRIMARY KEY (ID)
)
ENGINE=MyISAM;

DROP TABLE TBEXPORT_PARTICIPATION;

CREATE TABLE TBEXPORT_PARTICIPATION (
	ID_TOURNAMENT INT NOT NULL,
	ID_MEMBER INT NOT NULL,
	ID_BUY_IN INT,
	VALUE_BUY_IN INT,
	ID_GAIN INT,
	VALUE_GAIN INT,
	PRIMARY KEY(ID_TOURNAMENT, ID_MEMBER)
) 
ENGINE = MyISAM ;

DROP TABLE TB_SNG_WAR;

CREATE TABLE TB_SNG_WAR (
	DATE_SNG TIMESTAMP NOT NULL,
	SIZE_SNG VARCHAR(2) NOT NULL ,
	BUY_IN DOUBLE NOT NULL ,
	PLACE INT NOT NULL ,
	NAME VARCHAR(50) NOT NULL
) 
ENGINE = MyISAM COLLATE latin1_general_ci;